export const calendarSpecs = [
  {
    name: "ru-390-dark-bike-calendar",
    path: "/?gate=ru-390-dark-distance#distance",
    locale: "ru",
    theme: "dark",
    target: ".calendar-poster",
    viewport: { width: 390, height: 844 },
  },
  {
    name: "ru-1440-light-bike-calendar-disclosure",
    path: "/?phase=before#distance",
    locale: "ru",
    theme: "light",
    target: ".bike-calendar__details",
    expectedPhase: "before",
    expectedCalendarPhase: "far",
    expectedCalendarOpen: false,
    viewport: { width: 1440, height: 900 },
  },
  {
    name: "ru-390-light-bike-calendar-disclosure",
    path: "/?phase=before#distance",
    locale: "ru",
    theme: "light",
    target: ".bike-calendar__details",
    expectedPhase: "before",
    expectedCalendarPhase: "far",
    expectedCalendarOpen: false,
    viewport: { width: 390, height: 844 },
  },
  {
    name: "ru-1440-light-bike-calendar-active",
    path: "/?phase=active#distance",
    locale: "ru",
    theme: "light",
    target: ".calendar-current",
    expectedPhase: "active",
    expectedCalendarPhase: "active",
    expectedCalendarOpen: true,
    expectCalendarCurrent: true,
    viewport: { width: 1440, height: 900 },
  },
  {
    name: "ru-320-light-bike-calendar-sequence",
    path: "/?gate=ru-320-light-calendar-sequence#distance",
    locale: "ru",
    theme: "light",
    target: ".calendar-poster",
    viewport: { width: 320, height: 844 },
  },
  {
    name: "ru-390-light-diary-heading",
    path: "/?gate=ru-390-light-diary-heading#diary",
    locale: "ru",
    theme: "light",
    target: ".diary-story:not([hidden]) .diary-story__heading",
    viewport: { width: 390, height: 844 },
  },
  {
    name: "ru-390-dark-manifesto-copy",
    path: "/?gate=ru-390-dark-manifesto-copy#about",
    locale: "ru",
    theme: "dark",
    target: ".manifesto__copy",
    viewport: { width: 390, height: 844 },
  },
  {
    name: "ru-390-light-bike-calendar-segments",
    path: "/?gate=ru-390-light-calendar-segments#distance",
    locale: "ru",
    theme: "light",
    target: ".calendar-program__list",
    viewport: { width: 390, height: 844 },
  },
  {
    name: "en-320-light-bike-calendar-segments",
    path: "/en/?gate=en-320-light-calendar-segments#distance",
    locale: "en",
    theme: "light",
    target: ".calendar-program__list",
    viewport: { width: 320, height: 844 },
  },
  {
    name: "ru-390-light-bike-calendar-final-stage",
    path: "/?gate=ru-390-light-calendar-total#distance",
    locale: "ru",
    theme: "light",
    target: "#calendar-segment-10",
    viewport: { width: 390, height: 844 },
  },
  {
    name: "ru-320-light-bike-calendar-final-stage",
    path: "/?gate=ru-320-light-calendar-total#distance",
    locale: "ru",
    theme: "light",
    target: "#calendar-segment-10",
    viewport: { width: 320, height: 844 },
  },
  {
    name: "ru-1440-light-bike-calendar-sequence",
    path: "/?gate=ru-1440-light-calendar-sequence#distance",
    locale: "ru",
    theme: "light",
    target: ".calendar-poster",
    viewport: { width: 1440, height: 900 },
  },
  {
    name: "ru-1024-light-bike-calendar-sequence",
    path: "/?gate=ru-1024-light-calendar-sequence#distance",
    locale: "ru",
    theme: "light",
    target: ".calendar-poster",
    viewport: { width: 1024, height: 768 },
  },
  {
    name: "ru-1440-light-bike-calendar-rhythm",
    path: "/?gate=ru-1440-light-calendar-rhythm#distance",
    locale: "ru",
    theme: "light",
    target: ".calendar-program__rhythm",
    viewport: { width: 1440, height: 900 },
  },
  {
    name: "ru-1440-light-bike-calendar-finish",
    path: "/?gate=ru-1440-light-calendar-finish#distance",
    locale: "ru",
    theme: "light",
    target: ".calendar-program__row--finish",
    viewport: { width: 1440, height: 900 },
  },
  {
    name: "ru-1440-light-bike-calendar-final-stage",
    path: "/?gate=ru-1440-light-calendar-total#distance",
    locale: "ru",
    theme: "light",
    target: "#calendar-segment-10",
    viewport: { width: 1440, height: 900 },
  },
  {
    name: "ru-1440-light-athlete-sticky",
    path: "/?gate=ru-1440-light-athlete-sticky#viktor",
    locale: "ru",
    theme: "light",
    target: ".achievement-grid",
    viewport: { width: 1440, height: 900 },
  },
  {
    name: "ru-1440-light-partner-closing",
    path: "/?gate=ru-1440-light-partner-closing#partners",
    locale: "ru",
    theme: "light",
    target: ".partners__closing",
    viewport: { width: 1440, height: 900 },
  },
];
