export const closingPhaseSpecs = [
  {
    name: "ru-390-light-effort-video",
    path: "/?gate=ru-390-light-effort#top",
    locale: "ru",
    theme: "light",
    target: ".story-frame:nth-child(3)",
    blockVideo: false,
    viewport: { width: 390, height: 844 },
  },
  {
    name: "ru-390-light-footer-countdown",
    path: "/?gate=ru-390-light-footer#top",
    locale: "ru",
    theme: "light",
    target: ".site-footer__intro",
    viewport: { width: 390, height: 844 },
  },
  {
    name: "en-1440-system-top",
    path: "/en/?gate=en-1440-system#top",
    locale: "en",
    theme: "system",
    viewport: { width: 1440, height: 900 },
  },
  {
    name: "en-320-light-diary-stories",
    path: "/en/?gate=en-320-light-diary#diary",
    locale: "en",
    theme: "light",
    target: ".diary-archive",
    expectDiaryStories: true,
    viewport: { width: 320, height: 844 },
  },
  {
    name: "ru-1440-phase-before",
    path: "/?phase=before#top",
    locale: "ru",
    theme: "system",
    expectedPhase: "before",
    viewport: { width: 1440, height: 900 },
  },
  {
    name: "ru-1440-phase-active",
    path: "/?phase=active#top",
    locale: "ru",
    theme: "system",
    expectedPhase: "active",
    viewport: { width: 1440, height: 900 },
  },
  {
    name: "ru-1440-phase-finished",
    path: "/?phase=finished#top",
    locale: "ru",
    theme: "system",
    expectedPhase: "finished",
    viewport: { width: 1440, height: 900 },
  },
];
