export const diarySpecs = [
  {
    name: "ru-390-light-top",
    path: "/?gate=ru-390-light#top",
    locale: "ru",
    theme: "light",
    viewport: { width: 390, height: 844 },
  },
  {
    name: "ru-390-light-diary-stories",
    path: "/?gate=ru-390-light-diary#diary",
    locale: "ru",
    theme: "light",
    target: ".diary-archive",
    expectDiaryStories: true,
    viewport: { width: 390, height: 844 },
  },
  {
    name: "ru-1440-light-diary-stories-current",
    path: "/?gate=ru-1440-light-diary-stories#diary",
    locale: "ru",
    theme: "light",
    target: ".diary-stories",
    diaryStory: 0,
    expectDiaryStories: true,
    viewport: { width: 1440, height: 900 },
  },
  {
    name: "ru-390-light-diary-entry-mixed",
    path: "/?gate=ru-390-light-diary-entry-mixed#diary",
    locale: "ru",
    theme: "light",
    target: ".diary-story:not([hidden])",
    diaryStoryDate: "2026-07-06",
    diaryMedia: 2,
    expectDiaryStories: true,
    expectDiaryMedia: true,
    viewport: { width: 390, height: 844 },
  },
  {
    name: "ru-1440-light-diary-entry-mixed",
    path: "/?gate=ru-1440-light-diary-entry-mixed#diary",
    locale: "ru",
    theme: "light",
    target: ".diary-story:not([hidden]) .diary__gallery",
    diaryStoryDate: "2026-07-06",
    diaryMedia: 2,
    expectDiaryStories: true,
    expectDiaryMedia: true,
    viewport: { width: 1440, height: 900 },
  },
  {
    name: "ru-1440-light-diary-live",
    path: "/?gate=ru-1440-light-diary-live#diary",
    locale: "ru",
    theme: "light",
    target: ".diary-live",
    viewport: { width: 1440, height: 900 },
  },
  {
    name: "ru-390-light-diary-live",
    path: "/?gate=ru-390-light-diary-live#diary",
    locale: "ru",
    theme: "light",
    target: ".diary-live",
    viewport: { width: 390, height: 844 },
  },
  {
    name: "ru-390-light-diary-state-active",
    path: "/?phase=active#diary",
    locale: "ru",
    theme: "light",
    target: ".diary-live",
    expectedPhase: "active",
    viewport: { width: 390, height: 844 },
  },
  {
    name: "ru-390-light-diary-state-finished",
    path: "/?phase=finished#diary",
    locale: "ru",
    theme: "light",
    target: ".diary-live",
    expectedPhase: "finished",
    viewport: { width: 390, height: 844 },
  },
  {
    name: "ru-320-light-diary-stories",
    path: "/?gate=ru-320-light-diary#diary",
    locale: "ru",
    theme: "light",
    target: ".diary-archive",
    expectDiaryStories: true,
    viewport: { width: 320, height: 844 },
  },
];
