export const entryMenuSpecs = [
  {
    name: "ru-1440-light-hero-evidence",
    path: "/?gate=ru-1440-hero-evidence#top",
    locale: "ru",
    theme: "light",
    target: ".hero__evidence",
    viewport: { width: 1440, height: 900 },
  },
  {
    name: "en-390-light-hero-evidence",
    path: "/en/?gate=en-390-hero-evidence#top",
    locale: "en",
    theme: "light",
    target: ".hero__evidence",
    viewport: { width: 390, height: 844 },
  },
  {
    name: "ru-390-text-200-diary-live",
    path: "/?gate=ru-390-text-200-diary&text=200#diary",
    locale: "ru",
    theme: "light",
    target: ".diary-live",
    textScale: 200,
    viewport: { width: 390, height: 844 },
  },
  {
    name: "en-390-text-200-diary-live",
    path: "/en/?gate=en-390-text-200-diary&text=200#diary",
    locale: "en",
    theme: "light",
    target: ".diary-live",
    textScale: 200,
    viewport: { width: 390, height: 844 },
  },
  {
    name: "ru-1440-system-top",
    path: "/?gate=ru-1440-system#top",
    locale: "ru",
    theme: "system",
    viewport: { width: 1440, height: 900 },
  },
  {
    name: "ru-1440-system-menu",
    path: "/?gate=ru-1440-menu#top",
    locale: "ru",
    theme: "system",
    menuOpen: true,
    expectMenuFit: true,
    viewport: { width: 1440, height: 900 },
  },
  {
    name: "ru-1440-dark-proof-open",
    path: "/?gate=ru-1440-dark-proof#proof",
    locale: "ru",
    theme: "dark",
    proofOpen: true,
    viewport: { width: 1440, height: 900 },
  },
  {
    name: "ru-390-system-top",
    path: "/?gate=ru-390-system#top",
    locale: "ru",
    theme: "system",
    viewport: { width: 390, height: 844 },
  },
  {
    name: "ru-390-system-menu",
    path: "/?gate=ru-390-menu#top",
    locale: "ru",
    theme: "system",
    menuOpen: true,
    expectMenuScroll: true,
    viewport: { width: 390, height: 844 },
  },
  {
    name: "ru-390-system-menu-bottom",
    path: "/?gate=ru-390-menu-bottom#top",
    locale: "ru",
    theme: "system",
    menuOpen: true,
    menuBottom: true,
    expectMenuScroll: true,
    viewport: { width: 390, height: 844 },
  },
  {
    name: "ru-320-system-top",
    path: "/?gate=ru-320-system#top",
    locale: "ru",
    theme: "system",
    viewport: { width: 320, height: 844 },
  },
  {
    name: "ru-320-system-menu",
    path: "/?gate=ru-320-menu#top",
    locale: "ru",
    theme: "system",
    menuOpen: true,
    expectMenuScroll: true,
    viewport: { width: 320, height: 844 },
  },
  {
    name: "ru-390-text-200-menu",
    path: "/?gate=ru-390-text-200&text=200#top",
    locale: "ru",
    theme: "system",
    menuOpen: true,
    textScale: 200,
    viewport: { width: 390, height: 844 },
  },
  {
    name: "ru-390-text-200-menu-bottom",
    path: "/?gate=ru-390-text-200-bottom&text=200#top",
    locale: "ru",
    theme: "system",
    menuOpen: true,
    menuBottom: true,
    textScale: 200,
    viewport: { width: 390, height: 844 },
  },
  {
    name: "ru-390-keyboard-focus",
    path: "/?gate=ru-390-keyboard#top",
    locale: "ru",
    theme: "system",
    keyboardFocus: 3,
    viewport: { width: 390, height: 844 },
  },
  {
    name: "ru-1440-reduced-motion",
    path: "/?gate=ru-reduced-motion#top",
    locale: "ru",
    theme: "system",
    reducedMotion: "reduce",
    blockVideo: false,
    viewport: { width: 1440, height: 900 },
  },
  {
    name: "ru-1440-video-fallback",
    path: "/?gate=ru-video-fallback#top",
    locale: "ru",
    theme: "system",
    expectVideoFallback: true,
    viewport: { width: 1440, height: 900 },
  },
  ...[0.12, 0.5, 0.88].map((videoFrame, index) => ({
    name: `ru-1440-video-contrast-${index + 1}`,
    path: `/?gate=ru-video-contrast-${index + 1}#top`,
    locale: "ru",
    theme: "system",
    blockVideo: false,
    videoFrame,
    viewport: { width: 1440, height: 900 },
  })),
  {
    name: "ru-1280-forced-colors-top",
    path: "/?gate=ru-forced-colors#top",
    locale: "ru",
    theme: "system",
    forcedColors: "active",
    blockVideo: false,
    viewport: { width: 1280, height: 720 },
  },
  {
    name: "ru-1280-text-200-athlete",
    path: "/?gate=ru-text-200-athlete&text=200#about",
    locale: "ru",
    theme: "system",
    target: ".athlete",
    textScale: 200,
    viewport: { width: 1280, height: 720 },
  },
  {
    name: "ru-1280-text-200-bike-calendar-finish",
    path: "/?gate=ru-text-200-calendar-finish&text=200#distance",
    locale: "ru",
    theme: "light",
    target: ".calendar-program__row--finish",
    textScale: 200,
    viewport: { width: 1280, height: 720 },
  },
  {
    name: "ru-1280-text-200-footer",
    path: "/?gate=ru-text-200-footer&text=200#partners",
    locale: "ru",
    theme: "system",
    target: ".site-footer__intro",
    textScale: 200,
    viewport: { width: 1280, height: 720 },
  },
  {
    name: "en-1440-light-top",
    path: "/en/?gate=en-1440-light#top",
    locale: "en",
    theme: "light",
    viewport: { width: 1440, height: 900 },
  },
  {
    name: "en-390-dark-top",
    path: "/en/?gate=en-390-dark#top",
    locale: "en",
    theme: "dark",
    viewport: { width: 390, height: 844 },
  },
];
