export default {
  index: "04",
  date: "2026-05-09",
  href: "https://t.me/doroninvdele/629",
  image: "diary-2026-05-09.jpg",
  video: "diary-2026-05-09.mp4",
  videoDuration: "00:09",
  videoDurationIso: "PT9S",
  mediaWidth: 720,
  mediaHeight: 960,
  mediaAspect: "3 / 4",
  facts: [],
  content: {
    ru: {
      tabLabel: "Перед стартом",
      title: "Вернуть силы",
      imageAlt: "Виктор Доронин восстанавливается в бане после тренировочного сбора в Красной Поляне",
      videoLabel: "Видео из дневника подготовки: Виктор Доронин рассказывает о восстановлении перед стартом",
      videoPlayLabel: "Воспроизвести 9-секундное видео о восстановлении перед стартом",
      lead: "Сборы в Поляне подходят к концу - сегодня уже старт «Три горы» и дорога домой.",
      note: "Вчера отправились нашей компанией в баню.\n\nРусская баня в горах на сборах - это отдельная песня. Что может быть красивей?\n\nМы отправились в «<a href=\"https://t.me/russkiye_traditsii\" target=\"_blank\" rel=\"noopener noreferrer\">Русские традиции</a>» и могу сказать, что это одно из самых кайфовых мест для восстановления.\n\nА вы перед стартом как восстанавливайтесь?",
      externalLabel: "Откроется запись дневника Виктора от 9 мая в Telegram",
    },
    en: {
      tabLabel: "Before the start",
      title: "Recover to keep moving",
      imageAlt: "Viktor Doronin recovers in a banya after a training camp in Krasnaya Polyana",
      videoLabel: "Training diary video: Viktor Doronin talks about recovery before the next start",
      videoPlayLabel: "Play the 9-second video about pre-race recovery",
      lead: "The training camp in Polyana is coming to an end - today it’s already time for the Three Mountains start and the trip home.",
      note: "Yesterday our group went to the banya.\n\nA Russian banya in the mountains during a training camp is something else. What could be more beautiful?\n\nWe went to <a href=\"https://t.me/russkiye_traditsii\" target=\"_blank\" rel=\"noopener noreferrer\">Russkiye Traditsii</a>, and I can say it’s one of the most enjoyable places to recover.\n\nHow do you recover before a race?",
      externalLabel: "Opens Viktor’s May 9 training diary entry on Telegram",
    },
  },
};
